insert into public.companies (name, domain, logo_url) values
  -- Big Tech
  ('Google', 'google.com', 'https://www.google.com/s2/favicons?domain=google.com&sz=64'),
  ('Amazon', 'amazon.com', 'https://www.google.com/s2/favicons?domain=amazon.com&sz=64'),
  ('Apple', 'apple.com', 'https://www.google.com/s2/favicons?domain=apple.com&sz=64'),
  ('Meta', 'meta.com', 'https://www.google.com/s2/favicons?domain=meta.com&sz=64'),
  ('Microsoft', 'microsoft.com', 'https://www.google.com/s2/favicons?domain=microsoft.com&sz=64'),
  ('Netflix', 'netflix.com', 'https://www.google.com/s2/favicons?domain=netflix.com&sz=64'),
  ('Salesforce', 'salesforce.com', 'https://www.google.com/s2/favicons?domain=salesforce.com&sz=64'),
  ('Stripe', 'stripe.com', 'https://www.google.com/s2/favicons?domain=stripe.com&sz=64'),
  ('Airbnb', 'airbnb.com', 'https://www.google.com/s2/favicons?domain=airbnb.com&sz=64'),
  ('Uber', 'uber.com', 'https://www.google.com/s2/favicons?domain=uber.com&sz=64'),
  ('Lyft', 'lyft.com', 'https://www.google.com/s2/favicons?domain=lyft.com&sz=64'),
  ('Twitter', 'twitter.com', 'https://www.google.com/s2/favicons?domain=twitter.com&sz=64'),
  ('LinkedIn', 'linkedin.com', 'https://www.google.com/s2/favicons?domain=linkedin.com&sz=64'),
  ('Shopify', 'shopify.com', 'https://www.google.com/s2/favicons?domain=shopify.com&sz=64'),
  ('Atlassian', 'atlassian.com', 'https://www.google.com/s2/favicons?domain=atlassian.com&sz=64'),
  ('HubSpot', 'hubspot.com', 'https://www.google.com/s2/favicons?domain=hubspot.com&sz=64'),
  ('Notion', 'notion.so', 'https://www.google.com/s2/favicons?domain=notion.so&sz=64'),
  ('Figma', 'figma.com', 'https://www.google.com/s2/favicons?domain=figma.com&sz=64'),
  ('Slack', 'slack.com', 'https://www.google.com/s2/favicons?domain=slack.com&sz=64'),
  ('Zoom', 'zoom.us', 'https://www.google.com/s2/favicons?domain=zoom.us&sz=64'),
  ('Adobe', 'adobe.com', 'https://www.google.com/s2/favicons?domain=adobe.com&sz=64'),
  ('IBM', 'ibm.com', 'https://www.google.com/s2/favicons?domain=ibm.com&sz=64'),
  ('Oracle', 'oracle.com', 'https://www.google.com/s2/favicons?domain=oracle.com&sz=64'),
  ('ServiceNow', 'servicenow.com', 'https://www.google.com/s2/favicons?domain=servicenow.com&sz=64'),
  ('Workday', 'workday.com', 'https://www.google.com/s2/favicons?domain=workday.com&sz=64'),
  ('Twilio', 'twilio.com', 'https://www.google.com/s2/favicons?domain=twilio.com&sz=64'),
  ('Coinbase', 'coinbase.com', 'https://www.google.com/s2/favicons?domain=coinbase.com&sz=64'),
  ('Robinhood', 'robinhood.com', 'https://www.google.com/s2/favicons?domain=robinhood.com&sz=64'),
  ('DoorDash', 'doordash.com', 'https://www.google.com/s2/favicons?domain=doordash.com&sz=64'),
  ('Instacart', 'instacart.com', 'https://www.google.com/s2/favicons?domain=instacart.com&sz=64'),

  -- Tech / SaaS
  ('Spotify', 'spotify.com', 'https://www.google.com/s2/favicons?domain=spotify.com&sz=64'),
  ('Dropbox', 'dropbox.com', 'https://www.google.com/s2/favicons?domain=dropbox.com&sz=64'),
  ('Box', 'box.com', 'https://www.google.com/s2/favicons?domain=box.com&sz=64'),
  ('Palantir', 'palantir.com', 'https://www.google.com/s2/favicons?domain=palantir.com&sz=64'),
  ('Snowflake', 'snowflake.com', 'https://www.google.com/s2/favicons?domain=snowflake.com&sz=64'),
  ('Databricks', 'databricks.com', 'https://www.google.com/s2/favicons?domain=databricks.com&sz=64'),
  ('Cloudflare', 'cloudflare.com', 'https://www.google.com/s2/favicons?domain=cloudflare.com&sz=64'),
  ('MongoDB', 'mongodb.com', 'https://www.google.com/s2/favicons?domain=mongodb.com&sz=64'),
  ('Datadog', 'datadoghq.com', 'https://www.google.com/s2/favicons?domain=datadoghq.com&sz=64'),
  ('Okta', 'okta.com', 'https://www.google.com/s2/favicons?domain=okta.com&sz=64'),
  ('CrowdStrike', 'crowdstrike.com', 'https://www.google.com/s2/favicons?domain=crowdstrike.com&sz=64'),
  ('Palo Alto Networks', 'paloaltonetworks.com', 'https://www.google.com/s2/favicons?domain=paloaltonetworks.com&sz=64'),
  ('Splunk', 'splunk.com', 'https://www.google.com/s2/favicons?domain=splunk.com&sz=64'),
  ('Zendesk', 'zendesk.com', 'https://www.google.com/s2/favicons?domain=zendesk.com&sz=64'),
  ('Airtable', 'airtable.com', 'https://www.google.com/s2/favicons?domain=airtable.com&sz=64'),
  ('Intercom', 'intercom.com', 'https://www.google.com/s2/favicons?domain=intercom.com&sz=64'),
  ('Asana', 'asana.com', 'https://www.google.com/s2/favicons?domain=asana.com&sz=64'),
  ('OpenAI', 'openai.com', 'https://www.google.com/s2/favicons?domain=openai.com&sz=64'),
  ('Anthropic', 'anthropic.com', 'https://www.google.com/s2/favicons?domain=anthropic.com&sz=64'),
  ('Scale AI', 'scale.com', 'https://www.google.com/s2/favicons?domain=scale.com&sz=64'),
  ('SpaceX', 'spacex.com', 'https://www.google.com/s2/favicons?domain=spacex.com&sz=64'),
  ('Waymo', 'waymo.com', 'https://www.google.com/s2/favicons?domain=waymo.com&sz=64'),
  ('Rivian', 'rivian.com', 'https://www.google.com/s2/favicons?domain=rivian.com&sz=64'),
  ('GitHub', 'github.com', 'https://www.google.com/s2/favicons?domain=github.com&sz=64'),
  ('Vercel', 'vercel.com', 'https://www.google.com/s2/favicons?domain=vercel.com&sz=64'),

  -- Fintech / Startups
  ('PayPal', 'paypal.com', 'https://www.google.com/s2/favicons?domain=paypal.com&sz=64'),
  ('Square', 'squareup.com', 'https://www.google.com/s2/favicons?domain=squareup.com&sz=64'),
  ('Plaid', 'plaid.com', 'https://www.google.com/s2/favicons?domain=plaid.com&sz=64'),
  ('Brex', 'brex.com', 'https://www.google.com/s2/favicons?domain=brex.com&sz=64'),
  ('Rippling', 'rippling.com', 'https://www.google.com/s2/favicons?domain=rippling.com&sz=64'),
  ('Deel', 'deel.com', 'https://www.google.com/s2/favicons?domain=deel.com&sz=64'),
  ('Ramp', 'ramp.com', 'https://www.google.com/s2/favicons?domain=ramp.com&sz=64'),
  ('Gusto', 'gusto.com', 'https://www.google.com/s2/favicons?domain=gusto.com&sz=64'),
  ('Carta', 'carta.com', 'https://www.google.com/s2/favicons?domain=carta.com&sz=64'),
  ('Chime', 'chime.com', 'https://www.google.com/s2/favicons?domain=chime.com&sz=64'),

  -- Finance / Banking
  ('JPMorgan Chase', 'jpmorgan.com', 'https://www.google.com/s2/favicons?domain=jpmorgan.com&sz=64'),
  ('Goldman Sachs', 'goldmansachs.com', 'https://www.google.com/s2/favicons?domain=goldmansachs.com&sz=64'),
  ('Morgan Stanley', 'morganstanley.com', 'https://www.google.com/s2/favicons?domain=morganstanley.com&sz=64'),
  ('Bank of America', 'bankofamerica.com', 'https://www.google.com/s2/favicons?domain=bankofamerica.com&sz=64'),
  ('Wells Fargo', 'wellsfargo.com', 'https://www.google.com/s2/favicons?domain=wellsfargo.com&sz=64'),
  ('Citigroup', 'citi.com', 'https://www.google.com/s2/favicons?domain=citi.com&sz=64'),
  ('BlackRock', 'blackrock.com', 'https://www.google.com/s2/favicons?domain=blackrock.com&sz=64'),
  ('Fidelity', 'fidelity.com', 'https://www.google.com/s2/favicons?domain=fidelity.com&sz=64'),
  ('Capital One', 'capitalone.com', 'https://www.google.com/s2/favicons?domain=capitalone.com&sz=64'),
  ('American Express', 'americanexpress.com', 'https://www.google.com/s2/favicons?domain=americanexpress.com&sz=64'),
  ('Visa', 'visa.com', 'https://www.google.com/s2/favicons?domain=visa.com&sz=64'),
  ('Mastercard', 'mastercard.com', 'https://www.google.com/s2/favicons?domain=mastercard.com&sz=64'),
  ('Bloomberg', 'bloomberg.com', 'https://www.google.com/s2/favicons?domain=bloomberg.com&sz=64'),

  -- Consulting / Professional Services
  ('McKinsey & Company', 'mckinsey.com', 'https://www.google.com/s2/favicons?domain=mckinsey.com&sz=64'),
  ('Boston Consulting Group', 'bcg.com', 'https://www.google.com/s2/favicons?domain=bcg.com&sz=64'),
  ('Bain & Company', 'bain.com', 'https://www.google.com/s2/favicons?domain=bain.com&sz=64'),
  ('Deloitte', 'deloitte.com', 'https://www.google.com/s2/favicons?domain=deloitte.com&sz=64'),
  ('PwC', 'pwc.com', 'https://www.google.com/s2/favicons?domain=pwc.com&sz=64'),
  ('EY', 'ey.com', 'https://www.google.com/s2/favicons?domain=ey.com&sz=64'),
  ('KPMG', 'kpmg.com', 'https://www.google.com/s2/favicons?domain=kpmg.com&sz=64'),
  ('Accenture', 'accenture.com', 'https://www.google.com/s2/favicons?domain=accenture.com&sz=64'),
  ('Booz Allen Hamilton', 'boozallen.com', 'https://www.google.com/s2/favicons?domain=boozallen.com&sz=64'),

  -- Healthcare
  ('UnitedHealth Group', 'unitedhealthgroup.com', 'https://www.google.com/s2/favicons?domain=unitedhealthgroup.com&sz=64'),
  ('CVS Health', 'cvshealth.com', 'https://www.google.com/s2/favicons?domain=cvshealth.com&sz=64'),
  ('Johnson & Johnson', 'jnj.com', 'https://www.google.com/s2/favicons?domain=jnj.com&sz=64'),
  ('Pfizer', 'pfizer.com', 'https://www.google.com/s2/favicons?domain=pfizer.com&sz=64'),
  ('Abbott', 'abbott.com', 'https://www.google.com/s2/favicons?domain=abbott.com&sz=64'),
  ('Medtronic', 'medtronic.com', 'https://www.google.com/s2/favicons?domain=medtronic.com&sz=64'),
  ('Moderna', 'modernatx.com', 'https://www.google.com/s2/favicons?domain=modernatx.com&sz=64'),

  -- Retail / Consumer
  ('Walmart', 'walmart.com', 'https://www.google.com/s2/favicons?domain=walmart.com&sz=64'),
  ('Target', 'target.com', 'https://www.google.com/s2/favicons?domain=target.com&sz=64'),
  ('Home Depot', 'homedepot.com', 'https://www.google.com/s2/favicons?domain=homedepot.com&sz=64'),
  ('Nike', 'nike.com', 'https://www.google.com/s2/favicons?domain=nike.com&sz=64'),
  ('Starbucks', 'starbucks.com', 'https://www.google.com/s2/favicons?domain=starbucks.com&sz=64'),

  -- Media / Entertainment
  ('Disney', 'disney.com', 'https://www.google.com/s2/favicons?domain=disney.com&sz=64'),
  ('Warner Bros', 'warnerbros.com', 'https://www.google.com/s2/favicons?domain=warnerbros.com&sz=64'),
  ('NBCUniversal', 'nbcuniversal.com', 'https://www.google.com/s2/favicons?domain=nbcuniversal.com&sz=64'),

  -- Automotive / Aerospace
  ('Tesla', 'tesla.com', 'https://www.google.com/s2/favicons?domain=tesla.com&sz=64'),
  ('Ford', 'ford.com', 'https://www.google.com/s2/favicons?domain=ford.com&sz=64'),
  ('General Motors', 'gm.com', 'https://www.google.com/s2/favicons?domain=gm.com&sz=64'),
  ('Boeing', 'boeing.com', 'https://www.google.com/s2/favicons?domain=boeing.com&sz=64'),
  ('Lockheed Martin', 'lockheedmartin.com', 'https://www.google.com/s2/favicons?domain=lockheedmartin.com&sz=64'),
  ('Raytheon', 'rtx.com', 'https://www.google.com/s2/favicons?domain=rtx.com&sz=64'),

  -- Telecom
  ('AT&T', 'att.com', 'https://www.google.com/s2/favicons?domain=att.com&sz=64'),
  ('Verizon', 'verizon.com', 'https://www.google.com/s2/favicons?domain=verizon.com&sz=64'),
  ('T-Mobile', 't-mobile.com', 'https://www.google.com/s2/favicons?domain=t-mobile.com&sz=64')

on conflict (domain) do nothing;
